#!/bin/bash 

layout=$(setxkbmap -query | awk '/layout/{print $2}')
variant=$(setxkbmap -query | awk '/variant/{print $2}')
 
if [[ -n "$variant" ]]; then 
    echo "${layout}-${variant}"
else
    echo "${layout}"
fi
